name: app_artificial_intelligence
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  another_flutter_splash_screen: ^1.2.0
  cupertino_icons: ^1.0.6
  flutter:
    sdk: flutter
  flutter_inset_box_shadow: ^1.0.8
  flutter_riverpod: ^2.4.10
  go_router: ^13.2.0
  google_fonts: ^6.1.0
  http: ^1.2.0
  image_picker: ^1.0.7
  lottie: ^3.0.0
  page_transition: ^2.1.0
  tflite: ^1.1.2

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/dog_cat_model/
    - assets/flowers_model/
    - assets/frut_model/
    - assets/animals_model/
